tools:
  php_sim: true
  php_pdepend: true
  php_mess_detector: true
  php_analyzer: true
  sensiolabs_security_checker: true
  php_cs_fixer:
    config: { level: psr2 } # or psr1 if you would just like to get fixes for PSR1
  php_code_sniffer:
    config:
      standard: "PSR2"

filter:
  excluded_paths:
    - 'tests/*'
    - 'app/*'
    - 'features/*'

build:
  project_setup:
    before:
      - command: 'phantomjs2 --webdriver=8643'
        background: true                  
      - php app/console  assetic:dump --env=test
      - chmod -R 777 app/cache app/logs
  dependencies:
    override:
       - mysql -uroot -e 'CREATE DATABASE omnivalor_test'
       - mysql -uroot -e "CREATE USER 'symfony'@'localhost' IDENTIFIED BY ''";
       - mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'symfony'@'localhost' WITH GRANT OPTION";
       #- gunzip db.sql.gz
       #- mysql -uroot symfony < db.sql
       - composer install --no-interaction 
       - mysql -uroot -e 'DROP DATABASE omnivalor_test'
       - php app/console doctrine:database:create
       - php app/console doctrine:schema:create       

  environment:
    php:
      version: 5.6
    variables:
        APPLICATION_ENV: scrutinizer
    hosts:
      omnivalor.local: '127.0.0.1'
    selenium: true
    apache2:
      modules: ['rewrite']
      sites:
        samsoncms:
          web_root: 'www/'
          host: 'omnivalor.local/app_test.php'

  tests:
    override:
      - 'vendor/bin/behat -p scrutinizer'
