tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    # comment line below if this is paid scrutinizer project
    external_code_coverage: true
    php_cs_fixer:
            config: { level: psr2 } # or psr1 if you would just like to get fixes for PSR1
    php_code_sniffer:
            config:
                standard: "PSR2"

filter:
    excluded_paths:
        - 'ci/*'
        - 'tests/*'
        - 'fixtures/*'
        - 'features/*'

build:
  project_setup:
    before:
      -
        command: 'phantomjs --webdriver=8643'
        background: true
      # run migrations for now only http requests
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local
      - wget http://test.local

  dependencies:
    before:
      # Uncomment below to create database and user "test"
       #- gunzip test.sql.gz
       - mysql -uroot -e "CREATE DATABASE test"
       #- mysql -uroot test < test.sql
       - mysql -uroot -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'test'";
       - mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'test'@'localhost' WITH GRANT OPTION";

  environment:
    php:
      version: 5.5
    variables:
        APPLICATION_ENV: test
    hosts:
      # change to your actual testing domain
      test.local: '127.0.0.1'
    apache2:
      modules: ['rewrite']
      sites:
        test:
          web_root: 'www/'
          # change to your actual testing domain
          host: 'test.local'

  tests:
    override:
      - 'vendor/bin/behat -p test'
      #- 'vendor/bin/phpunit --coverage-clover=coverage.clover --coverage-text'

